import { INITIAL_IMAGE_STATE, type ImageState } from "../types";

export type ImagePreset = {
  id: string;
  label: string;
  description: string;
  family: string;
  archetype: string;
  variant: string;
  size: string;
  tags?: string[];
  state: Partial<ImageState>;
};

const buildPreset = (
  id: string,
  label: string,
  description: string,
  family: string,
  archetype: string,
  variant: string,
  size: string,
  tags: string[],
  state: Partial<ImageState>,
): ImagePreset => ({
  id,
  label,
  description,
  family,
  archetype,
  variant,
  size,
  tags,
  state: {
    ...INITIAL_IMAGE_STATE,
    ...state,
  },
});

const BASE_IMAGE_PRESETS: ImagePreset[] = [
  buildPreset(
    "editorial-frame",
    "Editorial Frame",
    "Crisp framed image with caption glass and calm composition.",
    "signature",
    "editorial",
    "frame",
    "lg",
    ["editorial", "frame", "caption", "calm"],
    {
      width: "720",
      height: "480",
      aspectRatio: "3/2",
      borderWidth: "1",
      borderStyle: "solid",
      borderColor: "#cbd5e1",
      boxShadowEnabled: true,
      boxShadowX: "0",
      boxShadowY: "18",
      boxShadowBlur: "36",
      boxShadowSpread: "0",
      boxShadowColor: "#0f172a26",
      captionEnabled: true,
      captionText: "Editorial frame",
      captionBgStyle: "glass",
      captionTextColor: "#f8fafc",
      captionFontSize: "16",
      hoverEffect: "lift",
      hoverLiftAmount: "12",
      entranceAnimation: "fade-in",
      ariaRole: "figure",
    },
  ),
  buildPreset(
    "glass-overlay",
    "Glass Overlay",
    "Soft glass treatment with overlay blend and subtle lift.",
    "signature",
    "glass",
    "overlay",
    "lg",
    ["glass", "overlay", "soft", "lift"],
    {
      borderRadiusMode: "uniform",
      borderRadiusUniform: "28",
      overlayEnabled: true,
      overlayColor: "#60a5fa",
      overlayOpacity: "26",
      overlayBlendMode: "screen",
      vignetteEnabled: true,
      vignetteIntensity: "34",
      vignetteSoftness: "56",
      vignetteColor: "#000000",
      captionEnabled: true,
      captionText: "Glass overlay",
      captionBgStyle: "glass",
      captionTextColor: "#ffffff",
      hoverEffect: "tilt",
      hoverTiltAmount: "8",
      entranceAnimation: "zoom-in",
    },
  ),
  buildPreset(
    "duotone-portrait",
    "Duotone Portrait",
    "High-contrast portrait with duotone layers and hover motion.",
    "signature",
    "portrait",
    "duotone",
    "md",
    ["portrait", "duotone", "high-contrast", "motion"],
    {
      src: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=1000&fit=crop",
      alt: "Portrait photograph",
      width: "540",
      height: "720",
      aspectRatio: "2/3",
      duotoneEnabled: true,
      duotoneColor1: "#0f172a",
      duotoneColor2: "#38bdf8",
      overlayEnabled: true,
      overlayColor: "#0f172a",
      overlayOpacity: "18",
      overlayBlendMode: "multiply",
      hoverEffect: "brightness",
      hoverIntensity: "115",
      entranceAnimation: "blur-in",
    },
  ),
  buildPreset(
    "masked-poster",
    "Masked Poster",
    "Poster-style crop with mask fade and cinematic framing.",
    "signature",
    "poster",
    "mask",
    "lg",
    ["poster", "mask", "cinematic", "caption"],
    {
      width: "800",
      height: "520",
      clipPathShape: "polygon",
      maskType: "linear-gradient",
      maskAngle: "180",
      maskStartOpacity: "100",
      maskEndOpacity: "0",
      captionEnabled: true,
      captionText: "Masked poster",
      captionPosition: "center",
      captionBgStyle: "solid",
      captionBgColor: "rgba(15,23,42,0.72)",
      captionTextColor: "#ffffff",
      hoverEffect: "zoom-in",
      hoverZoomScale: "1.05",
      entranceAnimation: "slide-up",
      ariaRole: "figure",
    },
  ),
  buildPreset(
    "3d-cinematic",
    "3D Cinematic",
    "Depth-forward image with perspective, tilt, and shadow.",
    "signature",
    "cinematic",
    "3d",
    "lg",
    ["3d", "cinematic", "depth", "tilt"],
    {
      perspective: "1200",
      rotateX: "10",
      rotateY: "-12",
      rotateZ: "1",
      dropShadowEnabled: true,
      dropShadowX: "0",
      dropShadowY: "18",
      dropShadowBlur: "26",
      dropShadowColor: "#0f172a33",
      hoverEffect: "tilt",
      hoverTiltAmount: "14",
      hoverDuration: "340",
      entranceAnimation: "slide-up",
    },
  ),
  buildPreset(
    "soft-portrait",
    "Soft Portrait",
    "Polished portrait with a gentle frame, softer filters, and calm motion.",
    "signature",
    "portrait",
    "soft",
    "md",
    ["portrait", "soft", "calm", "frame"],
    {
      src: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=1000&fit=crop",
      alt: "Soft portrait image",
      width: "520",
      height: "640",
      borderRadiusMode: "uniform",
      borderRadiusUniform: "36",
      brightness: "102",
      contrast: "104",
      saturation: "92",
      grayscale: "0",
      sepia: "6",
      filterOpacity: "100",
      boxShadowEnabled: true,
      boxShadowX: "0",
      boxShadowY: "12",
      boxShadowBlur: "32",
      boxShadowSpread: "0",
      boxShadowColor: "#0f172a22",
      hoverEffect: "zoom-out",
      hoverZoomScale: "0.98",
      entranceAnimation: "fade-in",
    },
  ),
  buildPreset(
    "cover-hero",
    "Cover Hero",
    "Large hero image with vivid overlay and content-center framing.",
    "signature",
    "hero",
    "cover",
    "xl",
    ["hero", "cover", "overlay", "editorial"],
    {
      src: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1600&h=900&fit=crop",
      alt: "Hero cover image",
      width: "1000",
      height: "560",
      aspectRatio: "16/9",
      objectFit: "cover",
      objectPositionX: "50",
      objectPositionY: "40",
      overlayEnabled: true,
      overlayColor: "#0f172a",
      overlayOpacity: "28",
      overlayBlendMode: "overlay",
      captionEnabled: true,
      captionText: "Cover hero",
      captionPosition: "bottom",
      captionBgStyle: "gradient",
      captionTextColor: "#ffffff",
      hoverEffect: "zoom-in",
      hoverZoomScale: "1.04",
      entranceAnimation: "fade-in",
    },
  ),
  buildPreset(
    "chrome-card",
    "Chrome Card",
    "Reflective framed card with polished contrast and a strong edge.",
    "signature",
    "chrome",
    "card",
    "lg",
    ["chrome", "card", "reflective", "frame"],
    {
      borderWidth: "2",
      borderStyle: "double",
      borderColor: "#cbd5e1",
      boxShadowEnabled: true,
      boxShadowX: "0",
      boxShadowY: "20",
      boxShadowBlur: "38",
      boxShadowSpread: "0",
      boxShadowColor: "#0f172a26",
      vignetteEnabled: true,
      vignetteIntensity: "22",
      vignetteSoftness: "42",
      vignetteColor: "#000000",
      hoverEffect: "lift",
      hoverLiftAmount: "10",
      entranceAnimation: "zoom-in",
      ariaRole: "figure",
    },
  ),
  buildPreset(
    "monochrome-story",
    "Monochrome Story",
    "Quiet monochrome treatment with restrained filters and serif mood.",
    "signature",
    "editorial",
    "monochrome",
    "lg",
    ["mono", "story", "editorial", "quiet"],
    {
      src: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=1200&h=900&fit=crop",
      alt: "Monochrome story image",
      saturation: "0",
      sepia: "10",
      grayscale: "18",
      contrast: "108",
      captionEnabled: true,
      captionText: "Monochrome story",
      captionBgStyle: "solid",
      captionBgColor: "rgba(15,23,42,0.68)",
      captionTextColor: "#ffffff",
      hoverEffect: "grayscale",
      entranceAnimation: "blur-in",
    },
  ),
  buildPreset(
    "luxe-cover",
    "Luxe Cover",
    "Premium cover image with glass caption and elevated shadow treatment.",
    "signature",
    "premium",
    "cover",
    "xl",
    ["luxe", "cover", "premium", "glass"],
    {
      src: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1600&h=1000&fit=crop",
      alt: "Luxe cover image",
      width: "960",
      height: "640",
      aspectRatio: "3/2",
      borderRadiusMode: "uniform",
      borderRadiusUniform: "24",
      boxShadowEnabled: true,
      boxShadowX: "0",
      boxShadowY: "22",
      boxShadowBlur: "44",
      boxShadowSpread: "0",
      boxShadowColor: "#0f172a30",
      captionEnabled: true,
      captionText: "Luxe cover",
      captionBgStyle: "glass",
      captionTextColor: "#ffffff",
      hoverEffect: "lift",
      hoverLiftAmount: "14",
      entranceAnimation: "zoom-in",
    },
  ),
  buildPreset(
    "gallery-tile",
    "Gallery Tile",
    "Compact gallery tile with balanced framing and minimal overlay.",
    "signature",
    "gallery",
    "tile",
    "sm",
    ["gallery", "tile", "compact", "balanced"],
    {
      width: "420",
      height: "420",
      aspectRatio: "1/1",
      borderRadiusMode: "uniform",
      borderRadiusUniform: "18",
      borderWidth: "1",
      borderStyle: "solid",
      borderColor: "#e2e8f0",
      hoverEffect: "zoom-in",
      hoverZoomScale: "1.03",
      entranceAnimation: "fade-in",
    },
  ),
  buildPreset(
    "halo-postcard",
    "Halo Postcard",
    "Soft halo-ed postcard with vignette, glow, and friendly framing.",
    "signature",
    "postcard",
    "halo",
    "md",
    ["postcard", "halo", "soft", "glow"],
    {
      src: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&h=900&fit=crop",
      alt: "Halo postcard image",
      overlayEnabled: true,
      overlayColor: "#38bdf8",
      overlayOpacity: "12",
      overlayBlendMode: "screen",
      vignetteEnabled: true,
      vignetteIntensity: "20",
      vignetteSoftness: "50",
      hoverEffect: "brightness",
      hoverIntensity: "110",
      entranceAnimation: "fade-in",
    },
  ),
  buildPreset(
    "contact-sheet",
    "Contact Sheet",
    "Neutral contact-sheet style with low distraction and maximum clarity.",
    "signature",
    "utility",
    "contact-sheet",
    "md",
    ["contact-sheet", "neutral", "grid", "utility"],
    {
      src: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1200&h=800&fit=crop",
      alt: "Contact sheet image",
      width: "480",
      height: "320",
      aspectRatio: "3/2",
      brightness: "100",
      contrast: "100",
      saturation: "100",
      overlayEnabled: false,
      captionEnabled: false,
      hoverEffect: "none",
      entranceAnimation: "none",
    },
  ),
];

type ImageTheme = {
  id: string;
  label: string;
  image: string;
  accent: string;
  accentSoft: string;
  shadow: string;
};

type ImageArchetype = {
  id: string;
  label: string;
  description: string;
  tags: string[];
  aspectRatio: ImageState["aspectRatio"];
  hoverEffect: ImageState["hoverEffect"];
  entranceAnimation: ImageState["entranceAnimation"];
  objectFit: ImageState["objectFit"];
  overlayEnabled: boolean;
  captionEnabled: boolean;
  borderRadius: string;
  maskType: ImageState["maskType"];
  clipPathShape: ImageState["clipPathShape"];
  duotoneEnabled: boolean;
  vignetteEnabled: boolean;
};

const THEMES: ImageTheme[] = [
  { id: "slate", label: "Slate", image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1600&h=900&fit=crop", accent: "#64748b", accentSoft: "#cbd5e1", shadow: "#0f172a22" },
  { id: "cobalt", label: "Cobalt", image: "https://images.unsplash.com/photo-1494526585095-c41746248156?w=1600&h=900&fit=crop", accent: "#3b82f6", accentSoft: "#bfdbfe", shadow: "#1d4ed833" },
  { id: "emerald", label: "Emerald", image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1600&h=900&fit=crop", accent: "#10b981", accentSoft: "#a7f3d0", shadow: "#065f4630" },
  { id: "sunset", label: "Sunset", image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1600&h=900&fit=crop", accent: "#f97316", accentSoft: "#fdba74", shadow: "#9a341233" },
  { id: "rose", label: "Rose", image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=1200&h=900&fit=crop", accent: "#f43f5e", accentSoft: "#fda4af", shadow: "#9f123933" },
  { id: "violet", label: "Violet", image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=1200&h=900&fit=crop", accent: "#8b5cf6", accentSoft: "#ddd6fe", shadow: "#5b21b633" },
  { id: "amber", label: "Amber", image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=1600&h=900&fit=crop", accent: "#f59e0b", accentSoft: "#fde68a", shadow: "#92400e33" },
  { id: "mint", label: "Mint", image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1600&h=900&fit=crop&sat=10", accent: "#14b8a6", accentSoft: "#99f6e4", shadow: "#115e5930" },
  { id: "arctic", label: "Arctic", image: "https://images.unsplash.com/photo-1545243424-0ce743321e11?w=1600&h=900&fit=crop", accent: "#38bdf8", accentSoft: "#bae6fd", shadow: "#0c4a6e33" },
  { id: "cherry", label: "Cherry", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=1200&h=900&fit=crop", accent: "#e11d48", accentSoft: "#fb7185", shadow: "#88133733" },
  { id: "obsidian", label: "Obsidian", image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1200&h=900&fit=crop&sat=-60", accent: "#334155", accentSoft: "#94a3b8", shadow: "#02061755" },
  { id: "indigo", label: "Indigo", image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=1600&h=900&fit=crop", accent: "#6366f1", accentSoft: "#c7d2fe", shadow: "#312e8150" },
];

const ARCHETYPES: ImageArchetype[] = [
  { id: "editorial-frame", label: "Editorial Frame", description: "Clean framed image with quiet caption structure.", tags: ["editorial", "frame", "caption", "calm"], aspectRatio: "3/2", hoverEffect: "lift", entranceAnimation: "fade-in", objectFit: "cover", overlayEnabled: false, captionEnabled: true, borderRadius: "12", maskType: "none", clipPathShape: "none", duotoneEnabled: false, vignetteEnabled: false },
  { id: "glass-overlay", label: "Glass Overlay", description: "Soft overlay treatment with a glassy surface.", tags: ["glass", "overlay", "soft", "premium"], aspectRatio: "16/9", hoverEffect: "tilt", entranceAnimation: "zoom-in", objectFit: "cover", overlayEnabled: true, captionEnabled: true, borderRadius: "28", maskType: "vignette", clipPathShape: "none", duotoneEnabled: false, vignetteEnabled: true },
  { id: "duotone-portrait", label: "Duotone Portrait", description: "High-contrast portrait with duotone layering.", tags: ["portrait", "duotone", "contrast", "motion"], aspectRatio: "2/3", hoverEffect: "brightness", entranceAnimation: "blur-in", objectFit: "cover", overlayEnabled: true, captionEnabled: false, borderRadius: "24", maskType: "none", clipPathShape: "none", duotoneEnabled: true, vignetteEnabled: false },
  { id: "masked-poster", label: "Masked Poster", description: "Poster crop with masked fade and cinematic framing.", tags: ["poster", "mask", "cinematic", "graphic"], aspectRatio: "3/2", hoverEffect: "zoom-in", entranceAnimation: "slide-up", objectFit: "cover", overlayEnabled: false, captionEnabled: true, borderRadius: "18", maskType: "linear-gradient", clipPathShape: "polygon", duotoneEnabled: false, vignetteEnabled: false },
  { id: "cinematic-3d", label: "Cinematic 3D", description: "Depth-forward image with perspective and lift.", tags: ["3d", "cinematic", "depth", "tilt"], aspectRatio: "16/9", hoverEffect: "tilt", entranceAnimation: "slide-up", objectFit: "cover", overlayEnabled: false, captionEnabled: false, borderRadius: "20", maskType: "none", clipPathShape: "none", duotoneEnabled: false, vignetteEnabled: false },
  { id: "soft-portrait", label: "Soft Portrait", description: "Calm portrait with gentle framing and restrained motion.", tags: ["portrait", "soft", "calm", "frame"], aspectRatio: "2/3", hoverEffect: "zoom-out", entranceAnimation: "fade-in", objectFit: "cover", overlayEnabled: false, captionEnabled: false, borderRadius: "36", maskType: "none", clipPathShape: "none", duotoneEnabled: false, vignetteEnabled: false },
  { id: "cover-hero", label: "Cover Hero", description: "Large editorial hero with bottom content support.", tags: ["hero", "cover", "overlay", "editorial"], aspectRatio: "16/9", hoverEffect: "zoom-in", entranceAnimation: "fade-in", objectFit: "cover", overlayEnabled: true, captionEnabled: true, borderRadius: "24", maskType: "none", clipPathShape: "none", duotoneEnabled: false, vignetteEnabled: true },
  { id: "chrome-card", label: "Chrome Card", description: "Reflective framed card with stronger edge treatment.", tags: ["chrome", "card", "reflective", "frame"], aspectRatio: "4/3", hoverEffect: "lift", entranceAnimation: "zoom-in", objectFit: "cover", overlayEnabled: false, captionEnabled: false, borderRadius: "18", maskType: "none", clipPathShape: "none", duotoneEnabled: false, vignetteEnabled: true },
  { id: "monochrome-story", label: "Monochrome Story", description: "Quiet monochrome image with editorial restraint.", tags: ["mono", "story", "editorial", "quiet"], aspectRatio: "3/2", hoverEffect: "grayscale", entranceAnimation: "blur-in", objectFit: "cover", overlayEnabled: false, captionEnabled: true, borderRadius: "16", maskType: "none", clipPathShape: "none", duotoneEnabled: false, vignetteEnabled: false },
  { id: "luxe-cover", label: "Luxe Cover", description: "Premium cover image with richer glass content support.", tags: ["luxe", "cover", "premium", "glass"], aspectRatio: "16/9", hoverEffect: "brightness", entranceAnimation: "fade-in", objectFit: "cover", overlayEnabled: true, captionEnabled: true, borderRadius: "24", maskType: "radial-gradient", clipPathShape: "none", duotoneEnabled: false, vignetteEnabled: true },
  { id: "halo-postcard", label: "Halo Postcard", description: "Soft postcard image with halo-ed overlay glow.", tags: ["postcard", "halo", "soft", "glow"], aspectRatio: "3/2", hoverEffect: "brightness", entranceAnimation: "fade-in", objectFit: "cover", overlayEnabled: true, captionEnabled: false, borderRadius: "20", maskType: "vignette", clipPathShape: "none", duotoneEnabled: false, vignetteEnabled: true },
  { id: "contact-sheet", label: "Contact Sheet", description: "Neutral utility view with low-distraction framing.", tags: ["utility", "neutral", "grid", "clear"], aspectRatio: "3/2", hoverEffect: "none", entranceAnimation: "none", objectFit: "cover", overlayEnabled: false, captionEnabled: false, borderRadius: "12", maskType: "none", clipPathShape: "none", duotoneEnabled: false, vignetteEnabled: false },
];

const SIZE_PROFILES = [
  { id: "sm", label: "Compact", width: "480", height: "320" },
  { id: "md", label: "Balanced", width: "640", height: "426" },
  { id: "lg", label: "Studio", width: "800", height: "520" },
  { id: "xl", label: "Hero", width: "1000", height: "560" },
];

function buildGeneratedPreset(
  theme: ImageTheme,
  archetype: ImageArchetype,
  size: (typeof SIZE_PROFILES)[number],
): ImagePreset {
  return {
    id: `${theme.id}-${archetype.id}-${size.id}`,
    label: `${theme.label} ${archetype.label} ${size.label}`,
    description: `${archetype.description} Tuned with the ${theme.label.toLowerCase()} family and ${size.label.toLowerCase()} scale.`,
    family: theme.id,
    archetype: archetype.id,
    variant: archetype.label,
    size: size.id,
    tags: [theme.id, archetype.id, size.id, ...archetype.tags],
    state: {
      ...INITIAL_IMAGE_STATE,
      src: theme.image,
      alt: `${theme.label} ${archetype.label} image`,
      width: size.width,
      height: size.height,
      aspectRatio: archetype.aspectRatio,
      objectFit: archetype.objectFit,
      borderRadiusMode: "uniform",
      borderRadiusUniform: archetype.borderRadius,
      borderWidth: archetype.id === "editorial-frame" || archetype.id === "chrome-card" ? "1" : "0",
      borderStyle: archetype.id === "chrome-card" ? "double" : "solid",
      borderColor: theme.accentSoft,
      boxShadowEnabled: true,
      boxShadowX: "0",
      boxShadowY: size.id === "xl" ? "18" : "12",
      boxShadowBlur: size.id === "xl" ? "36" : "28",
      boxShadowSpread: "0",
      boxShadowColor: theme.shadow,
      overlayEnabled: archetype.overlayEnabled,
      overlayColor: theme.accent,
      overlayOpacity: archetype.overlayEnabled ? "18" : "0",
      overlayBlendMode: archetype.id === "duotone-portrait" ? "multiply" : "screen",
      duotoneEnabled: archetype.duotoneEnabled,
      duotoneColor1: theme.accent,
      duotoneColor2: theme.accentSoft,
      clipPathShape: archetype.clipPathShape,
      maskType: archetype.maskType,
      vignetteEnabled: archetype.vignetteEnabled,
      vignetteIntensity: archetype.vignetteEnabled ? "24" : "0",
      vignetteSoftness: archetype.vignetteEnabled ? "46" : "0",
      vignetteColor: "#000000",
      captionEnabled: archetype.captionEnabled,
      captionText: `${theme.label} ${archetype.label}`,
      captionPosition: archetype.id === "cover-hero" ? "bottom" : "center",
      captionBgStyle: archetype.id.includes("glass") || archetype.id === "luxe-cover" ? "glass" : archetype.captionEnabled ? "solid" : "solid",
      captionBgColor: `color-mix(in srgb, ${theme.accent} 28%, rgba(15,23,42,0.72))`,
      captionTextColor: "#ffffff",
      hoverEffect: archetype.hoverEffect,
      entranceAnimation: archetype.entranceAnimation,
      brightness: archetype.id === "soft-portrait" ? "102" : "100",
      contrast: archetype.id === "duotone-portrait" ? "110" : "100",
      saturation: archetype.id === "monochrome-story" ? "0" : "100",
      grayscale: archetype.id === "monochrome-story" ? "18" : "0",
      dropShadowEnabled: archetype.id === "cinematic-3d",
      dropShadowX: "0",
      dropShadowY: "18",
      dropShadowBlur: "28",
      dropShadowColor: theme.shadow,
      perspective: archetype.id === "cinematic-3d" ? "1200" : "1000",
      rotateX: archetype.id === "cinematic-3d" ? "8" : "0",
      rotateY: archetype.id === "cinematic-3d" ? "-10" : "0",
      rotateZ: archetype.id === "cinematic-3d" ? "1" : "0",
      ariaRole: archetype.captionEnabled ? "figure" : "img",
      ariaHidden: false,
    },
  };
}

const GENERATED_IMAGE_PRESETS: ImagePreset[] = THEMES.flatMap((theme) =>
  ARCHETYPES.flatMap((archetype) =>
    SIZE_PROFILES.map((size) => buildGeneratedPreset(theme, archetype, size)),
  ),
);

export const IMAGE_PRESETS: ImagePreset[] = [
  ...BASE_IMAGE_PRESETS,
  ...GENERATED_IMAGE_PRESETS,
];
